### ISSUE TITLE
bug: `Tree` component does not properly set CursorLine highlight to line in window

### ISSUE THREAD

**Issue by vague2k** [grapp-dev/nui-components.nvim#40]
Hello! It seems like [line highlighting](https://github.com/grapp-dev/nui-components.nvim/blob/e6afc9f033098c22cd550b80111a49ad0d7d82b7/lua/nui-components/tree.lua#L224) does not work as intended when using a Tree or Tree like component such as select. I do not get `CursorLine` highlighting when hovering over.

Although I will say that a highlight does get applied in the component when layout is first rendered, but when it's focused the highlight gets cleared. This seems to be unexpected behavior. I will provide some screenshots below

Here is what the layout looks like on initial render.
 
<img width="323" alt="Screenshot 2024-04-27 at 3 50 29 PM" src="https://github.com/grapp-dev/nui-components.nvim/assets/121782036/062ed6a1-9743-483d-ab97-441c63968031">

This is what the Tree component looks like when focusing the Tree component, notice there's no `CursorLine` highlighting. I have made sure the theme has a `CursorLine` highlight as seen from the screenshot.

<img width="869" alt="Screenshot 2024-04-27 at 3 52 48 PM" src="https://github.com/grapp-dev/nui-components.nvim/assets/121782036/69d8cba3-8b94-4d16-8e85-d16a05425755">

While I think this is unexpected behavior, If there's some context I'm missing please let me know so I can close the issue! I also apologize for the rather obnoxious screenshots

**Comment by mobily** [comment]
@vague2k have you tried using the `NuiComponentsTreeNodeFocused` highlight group instead? (see: https://nui-components.grapp.dev/docs/components/tree#highlight-groups)

**Comment by vague2k** [comment]
Yes I have, and it does work, but in every example of the components being used that I've found from the showcase section the highlighting seems to be part of the component?

**Comment by mobily** [comment]
it's not part of the component implementation, you have to define highlight groups on your own, for instance, in the plugin config, as components don't define any by default
