### ISSUE TITLE
Wouldnt it be better to use icons for checkbox? [Suggestion]

### ISSUE THREAD

**Issue by siduck** [grapp-dev/nui-components.nvim#41]
![image](https://github.com/grapp-dev/nui-components.nvim/assets/59060246/c2be5781-3ca5-4278-916c-3d721d840f50)

**Comment by willothy** [comment]
You should be able to change the checked/unchecked sign to use icons if you want! I agree that maybe this should be the default though.

**Comment by siduck** [comment]
> should be able to change the checked/unchecked sign to use icons

nice!
